---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-issuers.yaml
  - external-secrets-stores.yaml
  # Commented out - these are examples only, uncomment when you have Azure Key Vault configured
  # - external-secrets-examples.yaml
  - sample-app-with-metrics.yaml
  - grafana-dashboard-sample-app.yaml
